### ISSUE TITLE
Compatibilité avec la box Tydom Home

### ISSUE THREAD

**Issue by jpvincent** [rezolv-fr/jeedoredaemon-dotnet#17]
Bonjour
Je vais faire un choix de marque de volets roulants, et Somfy ne donne pas entièrement satisfaction en compatibilité Jeedom à cause de l'absence de retour de position de volet. Mon installateur me propose des Delta Dore.
Dans la liste des box compatibles, je vois la V1 (retirée du marché), la V2 (plutôt alarme, plutôt très chère) et je ne vois pas la remplaçante de la V1 : la Tydom Home.
Ce plugin est-il ou va-t-il être compatible avec la Tydom Home ?

D'avance merci

**Comment by BlacKTM1190** [comment]
Hello
Pour répondre à ta question : elle est compatible avec Jeedom.
Avec Jeedore : vraissemblablement.
Cependant, pour le choix de marque, je dissocierais moteur de volets et protocole de communication.
Perso, j'ai des Somfy filaire avec des modules DD dans des boites à chaussette et derrière des Celiane.
Mais pour avoir plus d'avis, il vaut mieux passer sur Community.
Quant à Jeedore, Eli (rezolv-fr) a beaucoup oeuvré pour sa compatibilité mais il n'est plus maintenu.
La aussi des alternatives existent notament : [tydom2mqtt](https://github.com/fmartinou/tydom2mqtt/issues/30)

**Comment by jpvincent** [comment]
Merci pour ta réponse !
Je voulais poser la question de manière un peu officielle, car sur community il n'y avait justement pas de trace de réponse de l'auteur original.

J'avais vu ton projet également, mais je n'ai pas encore listé les possibilités et contraintes de MQTT.

J'ai noté des alternatives qui permettent effectivement de ne pas avoir de contrainte de marque de moteur (1 module FGR223 par volet ou 1 X4VR pour IPX800 pour 4 volets) : par contre je n'ai pas trouvé "module DD", peux tu m'en dire un peu plus ?

**Comment by BlacKTM1190** [comment]
J'ai des Tyxia 4630 pour les VR qui ne m'ont jamais fait défaut depuis 6 ans.
Ils ne se font plus et ont été remplacés par les 5630, plus compact.
J'ai plusieurs autres type de modules Delta Dore pour les lumieres, porte de garage,... aucun problème non plus, à part le Tywatt 2000 que j'ai du faire passer en garantie.

**Comment by jpvincent** [comment]
Magnifique, merci pour tes éclaircissements.
Je ferme le ticket je pense :)
