### ISSUE TITLE
Ne marche plus !!!

### ISSUE THREAD

**Issue by JeedHome44** [rezolv-fr/jeedoredaemon-dotnet#4]
Bonjour,
Hier soir, j'ai fait la mise à jour et ce matin je me rends compte que le plugin fait des erreurs et ne controle plus mes volets.
Tu as ajouté des lignes dans les configurations mais tu n'as pas dit dans le changelog pourquoi et que faut il mettre dedans!
Peux tu rapidement rectifier le problème?
Merci

**Comment by Heracles44** [comment]
J'ai fait un backdrop sur Jeedom pour retiré cette mise à jour. Je peux de nouveau controler mes volets mais je n'ai plus le retour d'état qui était juste parfait!
Pourquoi faire une mise à jour et retirer des fonctions?
Merci de remettre tout comme avant et de remettre le retour d'état des volets.
J'ai changé tous mes scénarios automatisés suite au retour d'état qui était avant dispo et maintenant non...
